// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: Getauth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetauthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accnamee  string                   `protobuf:"bytes,1,opt,name=Accnamee,proto3" json:"Accnamee,omitempty"`
	AccKey    string                   `protobuf:"bytes,2,opt,name=AccKey,proto3" json:"AccKey,omitempty"`
	Reqmethod string                   `protobuf:"bytes,3,opt,name=Reqmethod,proto3" json:"Reqmethod,omitempty"`
	ReqUrl    string                   `protobuf:"bytes,4,opt,name=ReqUrl,proto3" json:"ReqUrl,omitempty"`
	Reqheader map[string]*ListOfString `protobuf:"bytes,5,rep,name=reqheader,proto3" json:"reqheader,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetauthRequest) Reset() {
	*x = GetauthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Getauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetauthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetauthRequest) ProtoMessage() {}

func (x *GetauthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Getauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetauthRequest.ProtoReflect.Descriptor instead.
func (*GetauthRequest) Descriptor() ([]byte, []int) {
	return file_Getauth_proto_rawDescGZIP(), []int{0}
}

func (x *GetauthRequest) GetAccnamee() string {
	if x != nil {
		return x.Accnamee
	}
	return ""
}

func (x *GetauthRequest) GetAccKey() string {
	if x != nil {
		return x.AccKey
	}
	return ""
}

func (x *GetauthRequest) GetReqmethod() string {
	if x != nil {
		return x.Reqmethod
	}
	return ""
}

func (x *GetauthRequest) GetReqUrl() string {
	if x != nil {
		return x.ReqUrl
	}
	return ""
}

func (x *GetauthRequest) GetReqheader() map[string]*ListOfString {
	if x != nil {
		return x.Reqheader
	}
	return nil
}

type ListOfString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *ListOfString) Reset() {
	*x = ListOfString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Getauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfString) ProtoMessage() {}

func (x *ListOfString) ProtoReflect() protoreflect.Message {
	mi := &file_Getauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfString.ProtoReflect.Descriptor instead.
func (*ListOfString) Descriptor() ([]byte, []int) {
	return file_Getauth_proto_rawDescGZIP(), []int{1}
}

func (x *ListOfString) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

// The response message containing the greetings
type GetauthReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Authenication string `protobuf:"bytes,2,opt,name=authenication,proto3" json:"authenication,omitempty"`
}

func (x *GetauthReply) Reset() {
	*x = GetauthReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Getauth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetauthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetauthReply) ProtoMessage() {}

func (x *GetauthReply) ProtoReflect() protoreflect.Message {
	mi := &file_Getauth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetauthReply.ProtoReflect.Descriptor instead.
func (*GetauthReply) Descriptor() ([]byte, []int) {
	return file_Getauth_proto_rawDescGZIP(), []int{2}
}

func (x *GetauthReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetauthReply) GetAuthenication() string {
	if x != nil {
		return x.Authenication
	}
	return ""
}

var File_Getauth_proto protoreflect.FileDescriptor

var file_Getauth_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x63, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x41, 0x63, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x71, 0x55, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x71, 0x55, 0x72, 0x6c, 0x12, 0x4d,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x09, 0x72, 0x65, 0x71, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x5c, 0x0a,
	0x0e, 0x52, 0x65, 0x71, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x24, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32,
	0x62, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x20, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x68, 0x65, 0x6e, 0x63, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Getauth_proto_rawDescOnce sync.Once
	file_Getauth_proto_rawDescData = file_Getauth_proto_rawDesc
)

func file_Getauth_proto_rawDescGZIP() []byte {
	file_Getauth_proto_rawDescOnce.Do(func() {
		file_Getauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_Getauth_proto_rawDescData)
	})
	return file_Getauth_proto_rawDescData
}

var file_Getauth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Getauth_proto_goTypes = []interface{}{
	(*GetauthRequest)(nil), // 0: GetAthencticatio.GetauthRequest
	(*ListOfString)(nil),   // 1: GetAthencticatio.ListOfString
	(*GetauthReply)(nil),   // 2: GetAthencticatio.GetauthReply
	nil,                    // 3: GetAthencticatio.GetauthRequest.ReqheaderEntry
}
var file_Getauth_proto_depIdxs = []int32{
	3, // 0: GetAthencticatio.GetauthRequest.reqheader:type_name -> GetAthencticatio.GetauthRequest.ReqheaderEntry
	1, // 1: GetAthencticatio.GetauthRequest.ReqheaderEntry.value:type_name -> GetAthencticatio.ListOfString
	0, // 2: GetAthencticatio.Greeter.Getauthentication:input_type -> GetAthencticatio.GetauthRequest
	2, // 3: GetAthencticatio.Greeter.Getauthentication:output_type -> GetAthencticatio.GetauthReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Getauth_proto_init() }
func file_Getauth_proto_init() {
	if File_Getauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Getauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetauthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Getauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Getauth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetauthReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Getauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Getauth_proto_goTypes,
		DependencyIndexes: file_Getauth_proto_depIdxs,
		MessageInfos:      file_Getauth_proto_msgTypes,
	}.Build()
	File_Getauth_proto = out.File
	file_Getauth_proto_rawDesc = nil
	file_Getauth_proto_goTypes = nil
	file_Getauth_proto_depIdxs = nil
}
