// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.1
// source: GetEnv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type GetEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance string `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	Client   string `protobuf:"bytes,2,opt,name=Client,proto3" json:"Client,omitempty"`
}

func (x *GetEnvRequest) Reset() {
	*x = GetEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetEnv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvRequest) ProtoMessage() {}

func (x *GetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_GetEnv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvRequest.ProtoReflect.Descriptor instead.
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return file_GetEnv_proto_rawDescGZIP(), []int{0}
}

func (x *GetEnvRequest) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *GetEnvRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

// The response message containing the greetings
type GetEnvReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acctname string `protobuf:"bytes,1,opt,name=acctname,proto3" json:"acctname,omitempty"`
	Acctkey  string `protobuf:"bytes,2,opt,name=acctkey,proto3" json:"acctkey,omitempty"`
}

func (x *GetEnvReply) Reset() {
	*x = GetEnvReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetEnv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnvReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvReply) ProtoMessage() {}

func (x *GetEnvReply) ProtoReflect() protoreflect.Message {
	mi := &file_GetEnv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvReply.ProtoReflect.Descriptor instead.
func (*GetEnvReply) Descriptor() ([]byte, []int) {
	return file_GetEnv_proto_rawDescGZIP(), []int{1}
}

func (x *GetEnvReply) GetAcctname() string {
	if x != nil {
		return x.Acctname
	}
	return ""
}

func (x *GetEnvReply) GetAcctkey() string {
	if x != nil {
		return x.Acctkey
	}
	return ""
}

var File_GetEnv_proto protoreflect.FileDescriptor

var file_GetEnv_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x22, 0x43, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x74, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x74, 0x6b, 0x65, 0x79,
	0x32, 0x45, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetEnv_proto_rawDescOnce sync.Once
	file_GetEnv_proto_rawDescData = file_GetEnv_proto_rawDesc
)

func file_GetEnv_proto_rawDescGZIP() []byte {
	file_GetEnv_proto_rawDescOnce.Do(func() {
		file_GetEnv_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetEnv_proto_rawDescData)
	})
	return file_GetEnv_proto_rawDescData
}

var file_GetEnv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_GetEnv_proto_goTypes = []interface{}{
	(*GetEnvRequest)(nil), // 0: GetEnv.GetEnvRequest
	(*GetEnvReply)(nil),   // 1: GetEnv.GetEnvReply
}
var file_GetEnv_proto_depIdxs = []int32{
	0, // 0: GetEnv.Greeter.Getconfigs:input_type -> GetEnv.GetEnvRequest
	1, // 1: GetEnv.Greeter.Getconfigs:output_type -> GetEnv.GetEnvReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetEnv_proto_init() }
func file_GetEnv_proto_init() {
	if File_GetEnv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GetEnv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GetEnv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnvReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetEnv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GetEnv_proto_goTypes,
		DependencyIndexes: file_GetEnv_proto_depIdxs,
		MessageInfos:      file_GetEnv_proto_msgTypes,
	}.Build()
	File_GetEnv_proto = out.File
	file_GetEnv_proto_rawDesc = nil
	file_GetEnv_proto_goTypes = nil
	file_GetEnv_proto_depIdxs = nil
}
